{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-sa
  labels:
    {{- include "backend-posts-api.labels" . | nindent 4 }}
  annotations:
    {{- include "backend-posts-api.annotations" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
